### ISSUE TITLE
Implement registration system for volunteers

### ISSUE THREAD

**Issue by mark-craig** [mark-craig/engineerswithoutborders#1]
[https://www.pivotaltracker.com/n/projects/1887169](url)

features/volunteer_register.feature should pass completely.
This should be implemented using the Devise and SimpleForm gems as recommended via Piazza.
A relevant link: [https://github.com/plataformatec/simple_form/wiki/Simple-Form-with-Devise](https://github.com/plataformatec/simple_form/wiki/Simple-Form-with-Devise)

**Comment by mark-craig** [comment]
This is almost finished. Need to update cucumber scenarios to reflect the new User system and views.

**Comment by ChenCodes** [comment]
I'll be updating the cucumber scenarios
