### ISSUE TITLE
Calendar system

### ISSUE THREAD

**Issue by mark-craig** [mark-craig/engineerswithoutborders#10]
Projects should store important dates and deadlines. There should be a calendar view that shows upcoming events and deadlines for all projects.

**Comment by ChenCodes** [comment]
Implemented.

**Comment by ChenCodes** [comment]
![screen shot 2016-11-04 at 11 40 56 am](https://cloud.githubusercontent.com/assets/7213887/20018333/8e3d387e-a284-11e6-8980-f2a17ab1a3e0.png)
![screen shot 2016-11-04 at 11 40 50 am](https://cloud.githubusercontent.com/assets/7213887/20018335/8e4e5aaa-a284-11e6-92de-72f3cf1705fb.png)
