### ISSUE TITLE
Create templates for project detail page and prettify the User Interface

### ISSUE THREAD

**Issue by mark-craig** [mark-craig/engineerswithoutborders#9]
Projects should have a a nicely formatted view with images and other information about the project. All users should have access to these pages.

**Comment by ChenCodes** [comment]
I finished implemented uploading an image via the project form. Fadi is working on styling the page. 
![screen shot 2016-11-04 at 12 20 40 pm](https://cloud.githubusercontent.com/assets/7213887/20019452/9c2ea436-a289-11e6-812f-b8bc36a72586.png)
![screen shot 2016-11-04 at 12 20 10 pm](https://cloud.githubusercontent.com/assets/7213887/20019453/9c566b1a-a289-11e6-987e-d4418c48edf5.png)
